sequenceDiagram
    participant User
    participant Controller as CategoryInfoController
    participant Form as CategoryInfoForm
    participant Validator as CategoryInfoFormValidatorImpl
    participant Service as CategoryInfoService
    participant Repository as CategoryInfoRepository
    participant DB as 部品カテゴリー情報テーブル

    User->>Controller: GET /admin/CategoryInfo/search?keyword=xxx
    Controller->>Form: checkData(form)
    Form->>Validator: validate() // バリデーションチェック
    Validator-->>Form:
    Form-->>Controller:

    alt 入力エラーあり
        Controller->> Form: getErrorMessage()
        Form->>Validator:getErrorMessage()
        Validator-->>Form: エラーメッセージ設定
        Form-->>Controller: 
        Controller-->>User: return /admin/categoryInfo/index   // 検索画面にエラーメッセージを表示
    else 正常処理
        Controller->>Service: getCategoryInfoData(form) // 部品カテゴリリストのキーワード検索する
        Service->> Repository: findByKeyword(form.keyword)
        Repository->>DB: SELECT * FROm category_info WHERE name like ? 
        DB->> Repository: 部品カテゴリリスト返却
        Repository->>Service: 部品カテゴリリスト返却
        Service->>Controller: 部品カテゴリリスト返却
        Controller-->>User: return /admin/CategoryInfo/index  // 部品カテゴリー一覧画面へ
    end
